### ISSUE TITLE
Persistent Data - Docker

### ISSUE THREAD

**Issue by djmwj** [cdubz/babybuddy#46]
This is a great app! Thanks for all the hard work to make it possible. I have one issue that i am trying to resolve. I am running the babybuddy app via docker and I cannot make the data persistent between server restarts. What directories do I need to have as persistent volumes in order to get this to work?

This is my docker-compose file with the volumes I declare to create persistent data. What am I missing? Thanks!

##### docker-compose.yml
```
services:
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql
  app:
    env_file: docker.env
    build: .
    command: gunicorn -c /app/gunicorn.py babybuddy.wsgi
    volumes:
      - baby_data:/app
    ports:
      - "8000:8000"
    environment:
      - VIRTUAL_HOST=**************
      - LETSENCRYPT_HOST=**************
      - LETSENCRYPT_EMAIL=**************
      - VIRTUAL_PORT=8000
    depends_on:
      - db
    networks:
      - proxy-tier
      - default

volumes:
  baby_data:
  db:

networks:
  proxy-tier:
    external:
      name: webproxy
```

**Comment by cdubz** [comment]
I'll check this out when I get a chance. I'm not particularly well versed in Docker, but I wanted to do a test build in that environment again anyway.

**Comment by cdubz** [comment]
I played around with this but unforntaley didn’t get anywhere either. Docker is a bit of a beast. I’ll leave this open for a bit and would love to hear if you manage to figure out proper config. Sorry I couldn’t be more helpful!

**Comment by djmwj** [comment]
Thanks for looking into it. I have figured it out. the postgresql db image uses /var/lib/postgresql/data as the default data location. In order to have a persistent db, you must used a volume for this location. Additionally, in order to avoid re-migrating and collectingstatic content every time, I added /app as a named volume as well. 

So for the default docker-compose, it would look like:
Thanks for looking into it. I have figured it out. the postgresql db image uses /var/lib/postgresql/data as the default data location. In order to have a persistent db, you must used a volume for this location. Additionally, in order to avoid re-migrating and collectingstatic content every time, I added /app as a named volume as well. 

So for the default docker-compose, it would look like:
##### docker-compose.yml
```
version: "2"

services:
  db:
    image: postgres
    volumes: 
       - db:/var/lib/postgresql/data
  app:
    env_file: docker.env
    build: .
    command: gunicorn -c /app/gunicorn.py babybuddy.wsgi
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - baby_data:/app

volumes:
   db:
   baby_data:
```
